# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
