# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_api', '0002_auto_20160229_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='api_class',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='record',
            name='api_type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
