# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-18 05:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('link_api', '0005_auto_20160417_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcache',
            name='access_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 18, 5, 26, 34, 904921, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
